<?php
require_once './utils/auth.php';
require_once './utils/functions.php'
?>

<header>

    <a href="">Accueil</a>

    <nav>
        <?php if (isAuthenticated()) : ?>
            <a href="account.php">Mon compte</a>
        <?php else : ?>
            <a href="login.php">Connexion</a>
            <a href="signup.php">Inscription</a>
        <?php endif; ?>

        <?php if (isAdmin()): ?>
            <a href="admin">Admin</a>
        <?php endif; ?>
    </nav>

</header>