<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Akinator</title>
    <base href="http://localhost/3wa/php1/personality_project/akinator/" />
</head>

<body>

    <?php include_once 'template/layout/header.phtml'; ?>

    <?php include_once $template; ?>

    <?php include_once 'template/layout/footer.phtml'; ?>

</body>

</html>